### PR TITLE
Cross origin impl

### PR DESCRIPTION
**Pull request by 0lezhka**
Create ApplicationConstants class, which contains all important constants. Add cross-origin for api. Now angular client can make request on api.

### CODE REVIEW

**Comment by 0lezhka** [comment]
Before merging should be tested on deploy environment. @DmytroSavchuk can you deploy this branch to check if everything will work on deploy ?

**Comment by DmytroSavchuk** [comment]
image

**Comment by DmytroSavchuk** [comment]
I think everything is OK. So you can merge this branches.

**Review by DmytroSavchuk — APPROVED** [review]

**Review by OstapMelnychuk — COMMENTED** [review]
I have tested your code, but still got CORS policy error.
Screenshot_14

**Review by OstapMelnychuk — APPROVED** [review]

**Pull request merged**
